services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=${ES_SECURITY_ENABLED:-false}
      - xpack.security.http.ssl.enabled=${ES_HTTP_SSL_ENABLED:-false}
      - xpack.security.transport.ssl.enabled=${ES_TRANSPORT_SSL_ENABLED:-false}
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
    ulimits:
      memlock: { soft: -1, hard: -1 }
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./infra/certs:/usr/share/elasticsearch/config/certs:ro
    ports: ["9200:9200","9300:9300"]
    healthcheck:
      test: ["CMD","curl","-s","http://localhost:9200"]
      interval: 10s
      retries: 50
    profiles: ["dev","prod"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on: [elasticsearch]
    environment:
      - ELASTICSEARCH_HOSTS=${ES_HOSTS:-http://elasticsearch:9200}
      - ELASTICSEARCH_USERNAME=${KIBANA_SYSTEM_USER:-kibana_system}
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASS:-kibanachangeme}
    volumes:
      - ./infra/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports: ["5601:5601"]
    profiles: ["dev","prod"]

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    depends_on: [elasticsearch]
    volumes:
      - ./config/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/logstash/pipeline-postgresql.conf:/usr/share/logstash/pipeline/pipeline-postgresql.conf:ro
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
      - ES_HOST=${ES_OUT_HOST:-http://elasticsearch:9200}
      - ES_USER=${ES_OUT_USER:-elastic}
      - ES_PASS=${ES_OUT_PASS:-changeme}
    ports: ["5044:5044"]
    profiles: ["dev","prod","with-logstash"]

volumes:
  esdata:
